src/ResortMan.MvcApp/Areas/Staff/Controllers/BookingsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using ResortMan.MvcApp.Areas.Staff.ViewModels;
using ResortMan.Services;

namespace ResortMan.MvcApp.Areas.Staff.Controllers;

[Authorize(Roles = "Staff")]
[Area("Staff")]
public class BookingsController : Controller
{
	private readonly BookingService bookingsService;
	private readonly AccomodationsService accomodationsService;

	public BookingsController(BookingService bookingsService, AccomodationsService accomodationsService)
	{
		this.bookingsService = bookingsService;
		this.accomodationsService = accomodationsService;
	}

	public IActionResult Index(string? searchTerm)
	{
		BookingListingModel model;
		if (searchTerm != null)
		{
			model = new BookingListingModel();

			model.Bookings = bookingsService.SearchBooking(searchTerm);

			return View(model);
		}

		var list = bookingsService.GetBookings();
		model = new BookingListingModel()
		{
			Bookings = list,
		};
		return View(model);
	}

	[HttpGet]
	public ActionResult Action(int? id)
	{
		var model = new BookingActionModel();

		if (id == null)
			return BadRequest();

		var booking = bookingsService.GetBookingById(id.Value);

		if (booking == null)
			return NotFound();

		model.Id = booking.Id;
		model.FullName = booking.FullName;
		model.Email = booking.Email;
		model.PhoneNumber = booking.PhoneNumber;
		model.Duration = booking.Duration;
		model.Note = booking.Note;
		model.FromDate = booking.FromDate;
		model.AccomodationId = booking.AccomodationId;
		model.Status = booking.Status;

		model.Accomodations = accomodationsService.GetAccomodationsByPackageId(booking.Accomodation.AccomodationPackageId);

		return PartialView(model);
	}

	[HttpPost]
	public IActionResult Action(BookingActionModel model)
	{
		var result = false;

		var booking = bookingsService.GetBookingById(model.Id);

		if (booking == null)
			return BadRequest();

		booking.FullName = model.FullName;
		booking.Email = model.Email;
		booking.PhoneNumber = model.PhoneNumber;
		booking.Duration = model.Duration;
		booking.Note = model.Note;
		booking.FromDate = model.FromDate;
		booking.AccomodationId = model.AccomodationId;
		booking.Status = model.Status;
		result = bookingsService.UpdateBooking(booking);

		object json;
		if (result)
		{
			json = new { Success = true };

		}
		else
		{
			json = new { Success = false, Message = "Unable to perform action on Booking." };
		}

		return Json(json);
	}

	[HttpGet]
	public ActionResult Delete(int? id)
	{
		BookingActionModel model = new BookingActionModel();

		if (id == null)
			return BadRequest();

		var booking = bookingsService.GetBookingById(id.Value);

		if (booking == null)
			return NotFound();

		model.Id = booking.Id;

		return PartialView(model);
	}

	[HttpDelete]
	[ActionName("Delete")]
	public IActionResult DeleteConfirm(int id)
	{
		var booking = bookingsService.GetBookingById(id);

		bool result;
		if (booking == null)
			result = true;
		else
			result = bookingsService.DeleteBooking(booking.Id);

		object json;
		if (result)
		{
			json = new { Success = true };

		}
		else
		{
			json = new { Success = false, Message = "Unable to perform action on Accomodation Types." };
		}

		return Json(json);

	}
}

src/ResortMan.MvcApp/Controllers/BookingController.cs
using Microsoft.AspNetCore.Mvc;
using ResortMan.MvcApp.ViewModels;
using ResortMan.Services;

namespace ResortMan.MvcApp.Controllers;

public class BookingController : Controller
{
    private readonly BookingService bookingService;

    public BookingController(BookingService bookingService)
    {
        this.bookingService = bookingService;
    }
    public IActionResult Index(BookingFilter filter)
    {
        var model = new BookingIndexViewModel
        {
            Filter = filter,
        };

        if (ModelState.IsValid)
        {
            model.Bookings = bookingService.GetBookingsForUser(filter.PhoneNumber, filter.UserEmail);
        }

        return View(model);
    }
}

src/ResortMan.MvcApp/Areas/Staff/Views/Bookings/Action.cshtml
@model BookingActionModel

<div class="modal-content">
	<div class="modal-header">
		<h5 class="modal-title">
			@if (Model.Id > 0)
			{
				<span>Edit Accomodation Type</span>
			}
			else
			{
				<span>Create Accomodation Type</span>
			}
		</h5>
		<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
		</button>
	</div>
	<div class="modal-body">
		<form id="actionForm">
			<input type="hidden" name="Id" value="@Model.Id" />
			<div class="form-group">
				<label>Full Name</label>
				<input class="form-control" name="FullName" placeholder="Enter Full Name." value="@Model.FullName">
			</div>
			<div class="form-group">
				<label>Email</label>
				<textarea class="form-control" name="Email" placeholder="Enter Email.">@Model.Email</textarea>
			</div>
			<div class="form-group">
				<label>Accomodations</label>
				<select class="form-control" name="AccomodationId">

					@foreach (var item in Model.Accomodations)
					{
						<option value="@item.Id">@item.Name</option>
					}

				</select>
			</div>
			<div class="form-group">
				<label>Status</label>
				<select class="form-control" name="Status">

					@foreach (var item in Model.Statuses)
					{
						<option value="@item">@item</option>
					}

				</select>
			</div>
			<div class="form-group">
				<label>FromDate</label>
				<input class="form-control" name="FromDate" placeholder="Enter FromDate." value="@Model.FromDate">
			</div>
			<div class="form-group">
				<label>PhoneNumber</label>
				<input class="form-control" name="PhoneNumber" placeholder="Enter PhoneNumber." value="@Model.PhoneNumber">
			</div>
			<div class="form-group">
				<label>Duration</label>
				<input class="form-control" name="Duration" placeholder="Enter Duration." value="@Model.Duration">
			</div>
			<div class="form-group">
				<label>Note</label>
				<input class="form-control" name="Note" placeholder="Enter Note." value="@Model.Note">
			</div>
		</form>

		<div class="errorDiv">
		</div>
	</div>
	<div class="modal-footer">
		<button id="actionButton" type="button" class="btn btn-primary"><i class="fas fa-save mr-1"></i> Save</button>
		<button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fas fa-times mr-1"></i> Close</button>
	</div>
</div>



<script>
    $("#actionButton").click(function () {
        $.ajax({
            url: '@Url.Action("Action", "Bookings")',
            type: "post",
            data: $("#actionForm").serialize()
        })
            .done(function (response) {
                if (response.success) {
                    location.reload();
                }
                else {
                    $(".errorDiv").html(response.Message);
                }
            });
    });
</script>

src/ResortMan.MvcApp/Areas/Staff/Views/Bookings/Delete.cshtml
@model BookingActionModel
@{
}

<div class="modal-content">
	<div class="modal-header">
		<h5 class="modal-title">
			<span>Delete ? </span>
		</h5>
		<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
		</button>
	</div>
	<div class="modal-body">
		<form id="actionForm">
			<input type="hidden" name="Id" value="@Model.Id" />
		</form>
		<div class="alert alert-danger" role="alert">
			Do you wan't Delete AccomodationTypes ?
		</div>
		</div>
	<div class="modal-footer">
		<button id="actionButton" type="button" class="btn btn-danger"><i class="fas fa-trash-alt mr-1"></i> Delete</button>
		<button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fas fa-times mr-1"></i> Close</button>
	</div>
</div>




<script>
	$("#actionButton").click(function () {
		$.ajax({
			url: '@Url.Action("Delete", "Bookings")',
			type: "delete",
		})
			.done(function (response) {
				if (response.success) {
					window.location.href = "@Url.Action("Index", "Bookings")";
				}
				else {
					$(".errorDiv").html(response.Message);
				}
			});
	});
</script>

src/ResortMan.MvcApp/Areas/Staff/Views/Bookings/Index.cshtml
@model BookingListingModel
<div class="row">
    <div class="col col-lg-12">
        <h2>Booking</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col col-lg-12">
        <div class="input-group" style="padding-top: 20px;padding-bottom:15px">
            <form method="get" style="display:flex; width: 100%;">
                <input type="text"  class="form-control" placeholder="Search" id="searchTerm" name="searchTerm">
                <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search mr-1"></i> Search</button>
                <a class="btn btn-outline-secondary" href="@Url.Action("Index")"><i class="fas fa-redo-alt mr-1"></i> Reset</a>
            </form>
        </div>
    </div>
</div>

<partial name="_Listing" model="Model"></partial>

<!-- Modal -->
<div class="modal fade" id="actionModal" tabindex="-1">
    <div class="modal-dialog" role="document">
    </div>
</div>


@section Scripts {
    <script>
        $(".data-btn").click(function () {
            $.ajax({
                url: $(this).attr("data-href"),
            })
                .done(function (response) {
                    $("#actionModal .modal-dialog").html(response);
                });
        });
    </script>
}

src/ResortMan.MvcApp/Areas/Staff/Views/Bookings/_Listing.cshtml
@model BookingListingModel
@if(Model != null && Model.Bookings != null && Model.Bookings.Count() > 0)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Email</th>
                <th scope="col">Accomodation</th>
                <th scope="col">FromDate</th>
                <th scope="col">PhoneNumber</th>
                <th scope="col">Duration</th>
                <th scope="col">Note</th>
            </tr>
        </thead>
        <tbody >
            @foreach (var item in Model.Bookings)
            {
                <tr>
                    <td>
                        @item.FullName
                    </td>
                    <td>
                        @item.Email
                    </td>
                    <td>
                        @item.Accomodation.Name
                    </td>
                    <td>
                        @item.FromDate
                    </td>
                    <td>
                        @item.PhoneNumber
                    </td>
                    <td>
                        @item.Duration
                    </td>
                    <td>
                        @item.Note
                    </td>
                    <td>
                        <button data-href="@Url.Action("Action",  new { Id = item.Id })" type="button" class="data-btn btn btn-primary" data-bs-toggle="modal" data-bs-target="#actionModal"><i class="fas fa-pen mr-1"></i> Edit</button>
                        <button data-href="@Url.Action("Delete",  new { Id = item.Id })" type="button" class="data-btn btn btn-danger" data-bs-toggle="modal" data-bs-target="#actionModal"><i class="fas fa-trash-alt mr-1"></i> Delete</button>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else{
<div class="alert alert-warning" role="alert">
    Sorry! No records exist.
</div>
}