src/ResortMan.MvcApp/Areas/Dashboard/Controllers/AccomodationTypesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.DotNet.Scaffolding.Shared.Messaging;
using ResortMan.Entities;
using ResortMan.MvcApp.Areas.Dashboard.ViewModels;
using ResortMan.Services;

namespace ResortMan.MvcApp.Areas.Dashboard.Controllers;

[Area("Dashboard")]
[Authorize(Roles = "Administrator")]
public class AccomodationTypesController : Controller
{
	private readonly AccomodationTypesService accomodationTypesService;

	public AccomodationTypesController(AccomodationTypesService accomodationTypesService)
	{
		this.accomodationTypesService = accomodationTypesService;
	}

	public IActionResult Index(string? searchTerm)
	{
		AccomodationTypesListingModel model;
		if (searchTerm != null)
		{
			model = new AccomodationTypesListingModel();

			model.AccomodationTypes = accomodationTypesService.SearchAccomodationTypes(searchTerm);

			return View(model);
		}

		var list = accomodationTypesService.GetAccomodationTypes();
		model = new AccomodationTypesListingModel()
		{
			AccomodationTypes = list,
		};

		return View(model);
	}

	[HttpGet]
	public ActionResult Action(int? id)
	{
		AccomodationTypesActionModel model = new AccomodationTypesActionModel();

		if (id.HasValue)
		{
			var accomodationType = accomodationTypesService.GetAccomodationTypeById(id.Value);

			model.Id = accomodationType.Id;
			model.Name = accomodationType.Name;
			model.Description = accomodationType.Description;
		}

		return PartialView("_Action", model);
	}

	[HttpPost]
	public JsonResult Action(AccomodationTypesActionModel model)
	{
		var result = false;
		if (model.Id > 0)
		{
			var accomodationType = accomodationTypesService.GetAccomodationTypeById(model.Id);
			accomodationType.Name = model.Name;
			accomodationType.Description = model.Description;

			result = accomodationTypesService.UpdateAccomodationType(accomodationType);
		}
		else
		{
			AccomodationType accomodationType = new()
			{
				Name = model.Name,
				Description = model.Description,
			};

			result = accomodationTypesService.SaveAccomodationType(accomodationType);
		}


		object json;
		if (result)
		{
			json = new { Success = true };

		}
		else
		{
			json = new { Success = false, Message = "Unable to perform action on Accomodation Types." };
		}

		return Json(json);
	}

	[HttpGet]
	public ActionResult Delete(int id)
	{
		AccomodationTypesActionModel model = new AccomodationTypesActionModel();

		var accomodationType = accomodationTypesService.GetAccomodationTypeById(id);

		model.Id = accomodationType.Id;

		return PartialView("_Delete", model);
	}

	[HttpDelete]
	[ActionName("Delete")]
	public JsonResult DeleteConfirm(int id)
	{	
		var result = false;
		
		var accomodationType = accomodationTypesService.GetAccomodationTypeById(id);

		result = accomodationTypesService.DeleteAccomodationType(accomodationType);

		object json;
		if (result)
		{
			json = new { Success = true };

		}
		else
		{
			json = new { Success = false, Message = "Unable to perform action on Accomodation Types." };
		}

		return Json(json);
	}
}

src/ResortMan.MvcApp/Areas/Dashboard/Views/AccomodationTypes/Index.cshtml
@model AccomodationTypesListingModel
<div class="row">
    <div class="col col-lg-12">
        <h2>Accomodation Types</h2>
        <hr />
    </div>
</div>
<div class="row">
    <div class="col col-lg-12">
        <div class="input-group" style="padding-top: 20px;padding-bottom:15px">
            <form method="get" style="display:flex; width: 100%;">
                <input type="text"  class="form-control" placeholder="Search" id="searchTerm" name="searchTerm">
                <button class="btn btn-outline-primary" type="submit"><i class="fas fa-search mr-1"></i> Search</button>
                <a class="btn btn-outline-secondary" href="@Url.Action("Index", "AccomodationTypes")"><i class="fas fa-redo-alt mr-1"></i> Reset</a>
                <button data-href="@Url.Action("Action", "AccomodationTypes")" class="data-btn btn btn-outline-success" type="button" data-bs-toggle="modal" data-bs-target="#actionModal"><i class="fa-solid fa-plus"></i> Create </button>
            </form>
        </div>
    </div>
</div>

<partial name="_Listing" model="Model"></partial>

<!-- Modal -->
<div class="modal fade" id="actionModal" tabindex="-1">
    <div class="modal-dialog" role="document">
    </div>
</div>


@section Scripts {
    <script>
        $(".data-btn").click(function () {
            $.ajax({
                url: $(this).attr("data-href"),
            })
                .done(function (response) {
                    $("#actionModal .modal-dialog").html(response);
                });
        });
    </script>
}

src/ResortMan.MvcApp/Areas/Dashboard/Views/AccomodationTypes/_Action.cshtml
@model AccomodationTypesActionModel
<div class="modal-content">
	<div class="modal-header">
		<h5 class="modal-title">
			@if (Model.Id > 0)
			{
				<span>Edit Accomodation Type</span>
			}
			else
			{
				<span>Create Accomodation Type</span>
			}
		</h5>
		<button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
		</button>
	</div>
	<div class="modal-body">
		<form id="actionForm">
			<input type="hidden" name="Id" value="@Model.Id" />
			<div class="form-group">
				<label>Name</label>
				<input class="form-control" name="Name" placeholder="Enter Accomodation Type Name." value="@Model.Name">
			</div>
			<div class="form-group">
				<label>Description</label>
				<textarea class="form-control" name="Description" placeholder="Enter Accomodation Type Description.">@Model.Description</textarea>
			</div>
		</form>

		<div class="errorDiv">
		</div>
	</div>
	<div class="modal-footer">
		<button id="actionButton" type="button" class="btn btn-primary"><i class="fas fa-save mr-1"></i> Save</button>
		<button type="button" class="btn btn-secondary" data-bs-dismiss="modal"><i class="fas fa-times mr-1"></i> Close</button>
	</div>
</div>



<script>
    $("#actionButton").click(function () {
        $.ajax({
            url: '@Url.Action("Action", "AccomodationTypes")',
            type: "post",
            data: $("#actionForm").serialize()
        })
            .done(function (response) {
                if (response.success) {
                    location.reload();
                }
                else {
                    $(".errorDiv").html(response.Message);
                }
            });
    });
</script>

src/ResortMan.MvcApp/Areas/Dashboard/Views/AccomodationTypes/_Listing.cshtml
@model AccomodationTypesListingModel
@if(Model != null && Model.AccomodationTypes != null && Model.AccomodationTypes.Count() > 0)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Actions</th>
            </tr>
        </thead>
        <tbody >
            @foreach (var accomodationType in Model.AccomodationTypes)
            {
                <tr>
                    
                    <td>
                        @accomodationType.Name
                    </td>
                    <td>
                        @accomodationType.Description
                    </td>
                    <td>
                        <button data-href="@Url.Action("Action", "AccomodationTypes", new { Id = accomodationType.Id })" type="button" class="data-btn btn btn-primary" data-bs-toggle="modal" data-bs-target="#actionModal"><i class="fas fa-pen mr-1"></i> Edit</button>
                        <button data-href="@Url.Action("Delete", "AccomodationTypes", new { Id = accomodationType.Id })" type="button" class="data-btn btn btn-danger" data-bs-toggle="modal" data-bs-target="#actionModal"><i class="fas fa-trash-alt mr-1"></i> Delete</button>
                        
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else{
<div class="alert alert-warning" role="alert">
    Sorry! No records exist.
</div>
}