src/ResortMan.MvcApp/Areas/Dashboard/Controllers/RolesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http.HttpResults;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ResortMan.MvcApp.Areas.Dashboard.ViewModels;

namespace ResortMan.MvcApp.Areas.Dashboard.Controllers;

[Authorize(Roles = "Administrator")]
[Area("Dashboard")]
public class RolesController : Controller
{
	private readonly RoleManager<IdentityRole> roleManager;

	public RolesController(RoleManager<IdentityRole> roleManager)
	{
		this.roleManager = roleManager;
	}
	public async Task<IActionResult> IndexAsync()
	{
		var roles = await roleManager.Roles.Select(r => new RoleViewModel()
		{
			Id = r.Id,
			Name = r.Name!
		}).ToListAsync();

		return View(roles);
	}


	[ActionName("Action")]
	public async Task<IActionResult> CreateOrUpdateAsync(string? id)
	{
		if (id == null)
		{
			return PartialView("_Action");
		}

		var role = await roleManager.FindByIdAsync(id);

		if (role == null)
		{
			return NotFound();
		}

		var model = new RoleViewModel
		{
			Id = id,
			Name = role.Name!
		};

		return PartialView("_Action", model);
	}

	[ActionName("Action")]
	[HttpPost]
	public async Task<IActionResult> CreateOrUpdateAsync(string? id, RoleViewModel model)
	{
		IdentityRole? role;
		if (id == null)
		{
			role = new IdentityRole(model.Name);

			var createResult = await roleManager.CreateAsync(role);

			if (createResult.Succeeded)
			{
				return Ok();
			}
			else
			{
				return Problem(createResult.Errors.First().Description);
			}
		}
		else
		{
			role = await roleManager.FindByIdAsync(id);

			if (role == null)
			{
				return NotFound();
			}

			role.Name = model.Name;

			var updateResult = await roleManager.UpdateAsync(role);

			if (updateResult.Succeeded)
			{
				return Ok();
			}
			else
			{
				return Problem(updateResult.Errors.First().Description);
			}
		}
	}

	public async Task<IActionResult> DeleteAsync(string id)
	{
		var role = await roleManager.FindByIdAsync(id);

		if (role == null)
		{
			return NotFound();
		}

		return PartialView("_Delete", new RoleViewModel() { Id = role.Id });
	}

	[HttpDelete]
	[ActionName("Delete")]
	public async Task<IActionResult> DeleteConfirmAsync(string id)
	{
		var role = await roleManager.FindByIdAsync(id);

		if (role == null)
		{
			return Problem("Role does not exist");
		}

		var result = await roleManager.DeleteAsync(role);
		if (result.Succeeded)
		{
			return Ok();
		}
		else
		{
			return Problem(result.Errors.First().Description);
		}
	}
}

src/ResortMan.MvcApp/Areas/Dashboard/Controllers/UsersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ResortMan.Data;
using ResortMan.MvcApp.Areas.Dashboard.ViewModels;
using System.Data;

namespace ResortMan.MvcApp.Areas.Dashboard.Controllers;

[Authorize(Roles = "Administrator")]
[Area("Dashboard")]
public class UsersController : Controller
{
	private readonly ApplicationDbContext context;

	public UsersController(ApplicationDbContext context)
	{
		this.context = context;
	}
	public async Task<IActionResult> Index(string? searchTerm)
	{
		var query = context.Users
				.Include(u => u.UserRoles)
				.ThenInclude(ur => ur.Role)
				.AsQueryable();
		if (searchTerm != null)
		{
			searchTerm = searchTerm.Trim().ToUpperInvariant();
			query = query.Where(u => u.NormalizedUserName!.Contains(searchTerm));
		}

		var viewModel = new UsersListingViewModels()
		{
			SearchTerm = searchTerm,
			Users = await query.ToListAsync()
		};

		return View(viewModel);
	}

	public async Task<IActionResult> RoleAction(string id)
	{
		if (string.IsNullOrWhiteSpace(id))
		{
			return BadRequest();
		}
		var model = new UserRoleViewModel()
		{
			UserId = id,
			UserRole = await context.UserRoles
				.Include(ur => ur.Role)
				.Where(ur => ur.UserId == id)
				.Select(ur => ur.Role.Name!).FirstOrDefaultAsync(),
			Roles = await context.Roles.Select(r => r.Name!).ToListAsync()
		};

		return PartialView(model);
	}

	[HttpPost]
	public async Task<IActionResult> RoleAction(string id, UserRoleViewModel model)
	{
		if (string.IsNullOrWhiteSpace(id))
		{
			return Problem("Bad request", statusCode: 404);
		}

		if (ModelState.IsValid)
		{
			var isDelete = model.UserRole == null;

			IdentityRole? role = null;
			if (!isDelete)
			{
				role = await context.Roles.FirstOrDefaultAsync(r => r.Name == model.UserRole);
				if (role == null) return Problem("Role not found", statusCode: 404);
			}

			var userCurrentRole = await context.UserRoles
				.Include(ur => ur.Role)
				.Where(ur => ur.UserId == id)
				.FirstOrDefaultAsync();

			if (userCurrentRole != null)
				context.Remove(userCurrentRole);

			if (!isDelete)
			{
				var userRole = new ApplicationUserRole()
				{
					RoleId = role!.Id,
					UserId = id,
				};
				context.Add(userRole);
			}
			await context.SaveChangesAsync();

			return Ok();
		}

		return Problem();
	}

	public async Task<IActionResult> DeleteAsync(string id)
	{
		var user = await context.Users.FindAsync(id);

		if (user == null)
		{
			return NotFound();
		}

		return PartialView("_Delete", new ApplicationUser() { Id = user.Id });
	}

	[ActionName("Delete")]
	[HttpDelete]
	public async Task<IActionResult> DeleteConfirmAsync(string id)
	{
		var user = await context.Users.FindAsync(id);

		if (user == null)
		{
			return Problem("User does not exist");
		}
		context.Users.Remove(user);
		var isRemoved = await context.SaveChangesAsync() > 0;
		if (isRemoved)
		{
			return Ok();
		}
		else
		{
			return Problem("Cannot delete", statusCode: 400);
		}
	}
}

src/ResortMan.MvcApp/Controllers/AccomodationPackagesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ResortMan.Entities;
using ResortMan.MvcApp.Areas.Dashboard.ViewModels;
using ResortMan.Services;
using System.IO.Compression;
using System.IO;

namespace ResortMan.MvcApp.Controllers;

public class AccomodationPackagesController : Controller
{
    private readonly AccomodationPackagesService accomodationPackagesService;
    private readonly AccomodationTypesService accomodationTypesService;

    public AccomodationPackagesController(AccomodationPackagesService accomodationPackagesService,
        AccomodationTypesService accomodationTypesService)
    {
        this.accomodationPackagesService = accomodationPackagesService;
        this.accomodationTypesService = accomodationTypesService;
    }
    
    public IActionResult Details(int? id)
    {
        if (id == null)
            return BadRequest();

        var model = accomodationPackagesService.GetAccomodationPackageById(id.Value);

        if (model == null)
            return NotFound();

        return View(model);
    }
   
}

src/ResortMan.MvcApp/Areas/Dashboard/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />

    <title>@ViewData["Title"] - ResortMan.MvcApp</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.3.0/css/all.min.css" integrity="sha512-SzlrxWUlpfuzQ+pcUCosxcglQRNAq/DZjVsC0lE40xsADsfeQoEypE+enwcOiGjk/bSuGGKHEyjSoQ1zVisanQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="~/ResortMan.MvcApp.styles.css" asp-append-version="true" />
    <link href="~/css/styles.css" rel="stylesheet" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light"><a asp-area="" asp-controller="Home" asp-action="Index" class="fa-solid fa-hotel mr-1" style="color: #0077cc"></a> Resort Manager</div>
            <div class="list-group list-group-flush">
                <a href="@Url.Action("Index", "AccomodationTypes")" class="list-group-item list-group-item-action list-group-item-light ">
                    <i class="fa-solid fa-building mr-1 "></i> Accomodation Types
                </a>
                <a href="@Url.Action("Index", "AccomodationPackages")" class="list-group-item list-group-item-action bg-light">
                    <i class="fas fa-project-diagram mr-1"></i> Accomodation Packages
                </a>
                <a href="@Url.Action("Index", "Accomodations")" class="list-group-item list-group-item-action bg-light">
                    <i class="fas fa-map-pin mr-1"></i> Accomodation
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index", "Roles")">
                    <i class="fa-solid fa-user-gear mr-1"></i>  Roles
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" href="@Url.Action("Index", "Users")">
                    <i class="fa-solid fa-users-gear mr-1"></i>  Users
                </a>
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-primary" id="sidebarToggle"><i class="fa-solid fa-bars"></i></button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>

                    <partial name="_LoginPartial" />
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                @RenderBody()

            </div>
        </div>
    </div>
    <!-- Bootstrap core JS-->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/scripts.js"></script>
    <!-- Core theme JS-->
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>